name: Clarive Maven Plugin
description: Compile Maven projects from Clarive.
version: 1.0
icon: https://github.com/clarive/cla-maven-plugin/public/icon/maven.svg
url: https://github.com/clarive/cla-maven-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-maven-plugin
